USE [master]
GO

/****** Object:  Database [Movies]    Script Date: 03/10/2021 00:30:17 ******/
CREATE DATABASE [Movies]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Movies_Data', FILENAME = N'D:\Movie\Movies_Data.mdf' , SIZE = 25600KB , MAXSIZE = 40960KB , FILEGROWTH = 1024KB ), 
 FILEGROUP [Data] 
( NAME = N'Movies_Data2', FILENAME = N'D:\Movie\Movies_Data2.ndf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Movies_Log', FILENAME = N'D:\Movie\Movies_Log.ldf' , SIZE = 6144KB , MAXSIZE = 10240KB , FILEGROWTH = 1024KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Movies].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Movies] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Movies] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Movies] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Movies] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Movies] SET ARITHABORT OFF 
GO

ALTER DATABASE [Movies] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Movies] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Movies] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Movies] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Movies] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Movies] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Movies] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Movies] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Movies] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Movies] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Movies] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Movies] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Movies] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Movies] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Movies] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Movies] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Movies] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Movies] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Movies] SET  MULTI_USER 
GO

ALTER DATABASE [Movies] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Movies] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Movies] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Movies] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Movies] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Movies] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Movies] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Movies] SET  READ_WRITE 
GO

